[package]
name = "anode"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "anode"
path = "src/lib.rs"

[features]
default = []
gpu = ["cuda", "cuda_blas", "cuda_coll", "cuda_dnn", "gpudevicemem"]

[build-dependencies]
bindgen = "^0.32"
cc = "*"
walkdir = "*"

[dependencies]
rand = "*"
time = "*"
arithmetic = { path = "../libarithmetic" }
#async_execution = { path = "../async_execution" }
colorimage = { path = "../colorimage" }
cuda = { path = "../libcuda", optional = true }
cuda_blas = { path = "../libcuda_blas", optional = true }
cuda_coll = { path = "../cuda_coll", optional = true }
cuda_dnn = { path = "../libcuda_dnn", optional = true }
float = { path = "../libfloat" }
gpudevicemem = { path = "../gpudevicemem", optional = true }
lazy_static = "*"
memarray = { path = "../memarray" }
parking_lot = { version = "*", features = ["nightly"] }
rng = "*"
superdata = { path = "../superdata" }
typemap = "*"
