[package]
name = "anode"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "anode"
path = "src/lib.rs"

[features]
default = []
gpu = ["cuda", "cuda_blas", "cuda_coll", "cuda_dnn", "gpudevicemem"]
mpi = []

[build-dependencies]
bindgen = "^0.32"
cc = "*"
walkdir = "*"

[dev-dependencies]
colorimage = { path = "../colorimage" }
stb_image = { path = "../rust-stb-image" }
superdata = { path = "../superdata" }

[dependencies]
rand = "*"
time = "*"
arithmetic = { path = "../arithmetic" }
arrayidx = { path = "../arrayidx" }
#async_execution = { path = "../async_execution" }
cuda = { path = "../libcuda", optional = true }
cuda_blas = { path = "../cuda_blas", optional = true }
cuda_coll = { path = "../cuda_coll", optional = true }
cuda_dnn = { path = "../cuda_dnn", optional = true }
float = { path = "../libfloat" }
gpudevicemem = { path = "../gpudevicemem", optional = true }
lazy_static = "*"
memarray = { path = "../memarray", features = ["mkl"] }
parking_lot = { version = "*", features = ["nightly"] }
rng = "*"
typemap = "*"
