[package]
name = "anode"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "anode"
path = "src/lib.rs"

[features]
default = []
gpu = ["cuda", "cuda_blas", "cuda_dnn", "devicemem_gpu"]

[build-dependencies]
bindgen = "^0.32"
cc = "*"
#cc = { path = "../cc-rs-devel", features = ["parallel"] }
walkdir = "*"

[dependencies]
#lazy_static = "*"
rand = "*"
arithmetic = { path = "../libarithmetic" }
#async_execution = { path = "../async_execution" }
cuda = { path = "../libcuda", optional = true }
cuda_blas = { path = "../libcuda_blas", optional = true }
cuda_dnn = { path = "../libcuda_dnn", optional = true }
#devicemem_cuda = { path = "../libdevicemem_cuda", optional = true }
devicemem_gpu = { path = "../devicemem_gpu", optional = true }
memarray = { path = "../memarray" }
rng = "*"
